FGK-10x: use hubitat.zwave.commands.versionv2.VersionReport
Instead of hubitat.zwave.commands.versionv1.VersionReport. Primarily to
fix exception on zwaveEvent:

    java.lang.NullPointerException: Cannot invoke method multiply() on
    null object on line 597 (parse)