FGK-10x: Use zwave.getCommand instead of zwave.commandClass and ccObj?.command
Primarily to fix exception:

    groovy.lang.MissingMethodException: No signature of method:
    hubitat.zwave.Zwave.commandClass() is applicable for argument types:
    (java.lang.Short, java.lang.Integer) values: [49, 5] on line 215
    (parse)